proxy:
  blockchain-node:
    ethereum:
      global:
        main:
          enabled: true
          http: http://mainnet-node.ethereum-node:8545
          websocket: ws://mainnet-node.ethereum-node:8546
    polygon:
      global:
        main:
          enabled: true
          http: http://mainnet-node.polygon-node:8545
          websocket: ws://mainnet-node.polygon-node:8546

