version: '3.9'

x-common-variables: &common-variables
  APPLICATION_ENVIRONMENT: $APPLICATION_ENVIRONMENT
  SPRING_PROFILES_ACTIVE: $APPLICATION_ENVIRONMENT
  SPRING_CLOUD_CONSUL_CONFIG_ENABLED: $SPRING_CLOUD_CONSUL_CONFIG_ENABLED
  SPRING_CLOUD_BOOTSTRAP_ENABLED: $SPRING_CLOUD_BOOTSTRAP_ENABLED
  SPRING_CLOUD_SERVICEREGISTRY_AUTOREGISTRATION_ENABLED: $SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED
  SPRING_CLOUD_DISCOVERY_ENABLED: $SPRING_CLOUD_DISCOVERY_ENABLED
  LOGGING_LOGSTASH_TCP-SOCKET_ENABLED: $LOGGING_LOGSTASH_TCP_SOCKET_ENABLED
  LOGGING_LOGJSON_ENABLED: $LOGGING_LOGJSON_ENABLED

services:

  local-node-smart-proxy:
    build:
      context: ../proxy
      dockerfile: ../docker/Dockerfile
    image: protocol-node-smart-proxy
    environment:
      <<: *common-variables
      JAVA_OPTIONS: '-Xmx$PROTOCOL_SMART_PROXY_HEAP -Xms$PROTOCOL_SMART_PROXY_HEAP -XX:MaxDirectMemorySize=$PROTOCOL_SMART_PROXY_DIRECT_MEMORY'
    ports:
      - "${SMART_PROXY_EXPOSE_PORT}:8080"